apiVersion: batch/v1
kind: CronJob
metadata:
  name: chaoscmd
spec:
  schedule: "CHANGE SCHEDULE"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: chaoscmd
            image: docker.io/fbac/chaoscmd:latest
            imagePullPolicy: IfNotPresent
            args:
            - -pods-to-kill=1
            - -dry-run=false
          restartPolicy: OnFailure